### ISSUE TITLE
Cannot POST and req.session.passport undefined

### ISSUE THREAD

**Issue by bigdatacreative** [wojtekk/okta-auth#2]
Hey wojtekk!
First thank you for okta-auth !

In your okta-auth-sample you only have a app.get route. I did the same but okta sent me back a "cannot post" message.
So I wrote app.post route and it worked.
But when I call req.session.passport.user I get undefined... Well I'm a bit sad : (

What do you thing about the POST thing...?
Best!

nicolas

**Comment by bigdatacreative** [comment]
OK, resolved the post thing : )
Have now a PEM_read_bio_PUBKEY failed : )
will investigate ; )

**Comment by bigdatacreative** [comment]
OK solved the PEM_read_bio_PUBKEY
I only needed to remove ---BEGIN CERTIFICATE--- and  ---END CERTIFICATE--- in my cert config.
All good now, I get my user back too : )
Cheers and thank you for the good work

**Comment by wojtekk** [comment]
👍 :)
